spring:
  datasource:
    url: jdbc:mysql://jandy.cpet7qvxinol.ap-northeast-2.rds.amazonaws.com:3306/jandy
    username: admin
    password: asdfasdf

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
