spring:
  profiles:
    active: dev
    include: kakao

#
## jwt secret key 설정
#jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'
#
## 토큰 관련 secret Key 및 RedirectUri 설정
#app:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
#    tokenExpiry: 1800000
#    refreshTokenExpiry: 604800000
#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:8080/oauth/redirect